_schema: _schema
paths:
  uploads: public/uploads
  static: public
collections_config:
  src_content_blog:
    path: src/content/blog
    name: Content Blog
    icon: account_box
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_data:
    path: src/data
    name: Src Data
    icon: chat
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
